chipsalliance/caliptra-mcu-sw

- Cargo.lock
- Cargo.toml
- emulator/app/Cargo.toml
- emulator/app/src/main.rs
This is built into the standard library now.
This resolves https://github.com/chipsalliance/caliptra-mcu-sw/security/dependabot/1
> Remove atty from dependencies

- .cargo/config.toml
- xtask/src/apps_build.rs
- xtask/src/rom.rs
- xtask/src/runtime_build.rs
This optimizes memory reads and writes so that they don't have to be aligned, as this is not required for our CPU.
This saves abot 3 KB of instruction space in the runtime binary.
The VeeR CPU also supports bit manipulation instructions, but we don't have complete support for those in the emulator, so I left that as a TODO. That saves a few hundred bytes more (for now).
> Compile with unaligned-scalar-mem feature

- .cargo/config.toml
- Cargo.lock
- Cargo.toml
- emulator/periph/src/i3c.rs
- runtime/Cargo.toml
- runtime/i3c/Cargo.toml
- runtime/i3c/src/core.rs
- runtime/i3c/src/hil.rs
- runtime/i3c/src/lib.rs
- runtime/src/board.rs
- runtime/src/chip.rs
This does the initialization sequence, routes interrupts, and does passes reads and writes to the clients.
I haven't had a chance to do much testing yet, but that will be easier once the peripheral is more complete.
> i3c: Start basic driver

- .gitignore
- emulator/periph/src/flash_ctrl.rs
- registers/generated-emulator/src/el2_pic.rs
- registers/generated-emulator/src/flash.rs
- registers/generated-emulator/src/i3c.rs
- registers/generated-emulator/src/mbox.rs
- registers/generated-emulator/src/sha512_acc.rs
- registers/generated-emulator/src/soc.rs
- xtask/src/registers.rs
If a field is read-only, we shouldn't generate write methods for it. Likewise if a field is write-only, we shouldn't generate read methods for it.
Fixes #37
> registers: Honor read-only / write-only

- Cargo.lock
- Cargo.toml
- emulator/app/src/i3c_socket.rs
- emulator/app/src/main.rs
- emulator/bus/src/register.rs
- emulator/periph/Cargo.toml
- emulator/periph/src/i3c.rs
- emulator/periph/src/i3c_protocol.rs
- runtime/Cargo.toml
- runtime/i3c/src/core.rs
- runtime/src/board.rs
- runtime/src/chip.rs
- runtime/src/io.rs
- runtime/src/main.rs
- runtime/src/tests.rs
- tests/integration/Cargo.toml
- tests/integration/src/lib.rs
- xtask/src/main.rs
- xtask/src/precheckin.rs
- xtask/src/runtime.rs
- xtask/src/runtime_build.rs
This progresses more on the I3C peripheral, correctly queueing writes how the hardware does.
We also start on writing a socket protocol so that another thread or program can send reads and writes to the I3C bus. This hasn't been teste yet though.
I noticed two bugs that I will address in separate PRs:
* The I3C interrupts are not quite working yet. When enabled, they are routed correctly to the kernel handler, but keep getting retriggered and not handled properly. I've disabled the interrupts for now, so the read/write methods need to be called manually.
* Alarms are not firing properly. I tried to work around the interrupts not handling correctly by scheduling an alarm to call the read/write methods periodically, but the alarms never fire. I've noticed something similar to this before. I …
> I3C peripheral updates and integration tests

- .cargo/config.toml
- runtime/src/board.rs
- xtask/src/apps_build.rs
- xtask/src/rom.rs
- xtask/src/runtime_build.rs
Before:
```
cargo t  14.69s user 7.03s system 161% cpu 13.420 total
```
After:
```
cargo t  12.20s user 5.38s system 182% cpu 9.612 total
```
We consolidate RUSTFLAGS so that they are entirely in `.cargo/config.toml` -- this speeds up compiles since we aren't modifying `RUSTFLAGS` as part of `cargo xtask *-build` (which triggers recompiles). This also means we only need to worry about the flags in `.cargo/config.toml`.
Putting all of the `RUSTFLAGS` in `.cargo/config.toml` is mostly equivalent to passing them as an environment variable: there was a 100 byte difference in the application build, but it's not clear why.
We also add a filesystem cache of the result of finding the `sysroot`. For some reason, repeated calculation of it can be expensive (adds multiple seconds to the build). …
> Speed up compiles and clean up RUSTFLAGS

- Cargo.lock
- emulator/cpu/src/internal_timers.rs
- runtime/apps/pldm/src/riscv.rs
- runtime/kernel_layout.ld
- runtime/src/board.rs
- runtime/src/timers.rs
- xtask/Cargo.toml
- xtask/src/apps_build.rs
- xtask/src/runtime_build.rs
Fix several bugs related to alarms not firing in applications:
* Emulated internal timers were not handling wraparound correctly when checking how long to wait for the next interrupt. If the time had already passed for the next interrupt, then the function would underflow and return a value near u32::MAX, so the interrupt would be scheduled for the distant future instead of firing immediately.
* Fix alarm example code to sleep the correct amount of time.
* Application RAM was not being put in the correct location in the linker script. This caused issues with sharing memory with the kernel, as it was in the wrong region of RAM, which manifested as errors when printing to the console.
* Remove weird BSS workaround in the runtime linking, as we would only need it for certain ARM platforms.
* …
> Timer wraparound fix; app RAM address calculation

- Cargo.toml
- emulator/app/src/gdb/gdb_target.rs
We add debug symbols to compiled ELF files (does not affect final runtime binary).
And we allow gdb to read and write arbitrary memory, since the first thing it seems to do when it starts is to try to read 0xffffffff, which is not valid. This makes gdb support a bit more robust.
To use:
Compile the binaries.
```shell
cargo xtask runtime-build
```
In one shell, start the emulator manually:
```shell
cargo run -p emulator -- --rom target/riscv32imc-unknown-none-elf/release/rom -f target/riscv32imc-unknown-none-elf/release/runtime -g 3333
```
In another shell, connect with `gdb-multiarch`, and start debugging. You'll need to manually set the PC to `0x40000080` to start.
```shell
gdb-multiarch target/riscv32imc-unknown-none-elf/release/runtime
(gdb) target remote localhost:3333
(gdb) break …
```
> Support running under gdb-multiarch

- Cargo.lock
- Cargo.toml
- README.md
- emulator/bus/src/clock.rs
- emulator/periph/src/i3c.rs
- emulator/periph/src/i3c_protocol.rs
- romtime/Cargo.toml
- romtime/src/lib.rs
- runtime/Cargo.toml
- runtime/i3c/Cargo.toml
- runtime/i3c/src/core.rs
- runtime/src/chip.rs
- runtime/src/main.rs
- runtime/src/tests.rs
- runtime/src/timers.rs
This maps the internal queues in the I3C emulator peripheral to the interrupt controller, and modifies the tests so that they no longer manually poll.
I also added a new package, `romtime`, for drivers and utilities that are useful for both ROM and Runtime. For now, this contains an implementation of `print!` and `println!` that output to the emulator UART immediately, which is useful for both ROM and when running in Tock kernel when `debug!` may not be available (such as during tests or interrupts).
> Add interrupts support for I3C target

- emulator/cpu/src/cpu.rs
- emulator/cpu/src/csr_file.rs
- emulator/periph/src/root_bus.rs
- rom/src/io.rs
- romtime/src/lib.rs
- runtime/kernel_layout.ld
- runtime/src/board.rs
- runtime/src/chip.rs
- runtime/src/io.rs
- runtime/src/main.rs
- runtime/src/pmp.rs
- tests/hello/src/hello.rs
- tests/hello/src/start.S
I wasn't able to use an existing PMP layout due to our potential for multiple MMIO blocks as well as our unified RAM block: the existing PMP layouts that Tock has built in expect things to be aligned to neater boundaries with power of two sizes.
So, I modified the standard kernel EPMP layout to support what we need.
The "E" is used to indicate we support the SMEPMP extension, which provides some additional mode bits that allow more fine-grained control of shared areas between machine and user mode and allowing us to set a default deny all policy.
I moved around our memory map a little to make the PMP setup a little easier and reduce the number of regions we need, but left it flexible enough that we can still accommodate whatever memory map changes we need to make in the future. I moved …
> runtime: Enable PMP

- runtime/dma/Cargo.toml
- runtime/dma/src/hil.rs
- runtime/dma/src/lib.rs
- runtime/mailbox/Cargo.toml
- runtime/mailbox/src/hil.rs
- runtime/mailbox/src/lib.rs
Define HIL interfaces for Caliptra Mailbox and DMA.
This is based on the mailbox functionality defined in :
https://github.com/chipsalliance/caliptra-rtl/blob/main/docs/CaliptraIntegrationSpecification.md#mailbox
and the DMA operation in:
https://github.com/chipsalliance/caliptra-ss/blob/main/docs/Caliptra%202.0%20Subsystem%20Specification%201.pdf
> Add HIL interfaces for DMA and Caliptra Mailbox

- Cargo.lock
- Cargo.toml
- runtime/apps/libtock/runner/Cargo.toml
This was pulled back in by libtock/runner.
Fixes #73
> Update clap to avoid atty dependency

- runtime/apps/example/src/main.rs
Functionally there should be no difference because of this PR, as this function is not even called unless the feature is enabled.
But, before, you can see that when running the runtime that it is blocked keyboard input before the async sleeps will finish, while after this fix, it is not.
This functionality makes no sense. The `cfg!()` macro should be evaluated to `if false`, which should remove the code block entirely from the resulting binary.
Switching it to use this double `cfg` pattern removes 2 KB from the application binary, and removes this confusing keyboard behavior.
I suspect this is due to a compiler bug. It seems to be present even on the latest nightly compilers as well.
I'm going to keep investigating this and if applicable, report it to the Rust compiler devs.
> Disable MCTP user loopback tests really, really hard when disabled

- emulator/bus/src/clock.rs
- emulator/cpu/src/cpu.rs
Otherwise, if the CPU is busy with another interrupt, then additional interrupts are dropped and never sent to the interrupt handler. This is different from how the real CPU works, where the interrupt would keep being asserted until the the interrupt handler re-enables interrupts (when it jumps out of machine mode).
This was causing problems with our test code sometimes as the timer interrupts were getting lost randomly.
> emulator: Save interrupts to be processed later in action loop

- xtask/src/apps_build.rs
The total size calculation in the TBF header was incorrect due to a missing TBF header. This caused failures when loading multiple processes in the kernel, as the kernel relies on the total size in the TBF header to locate the next available app on flash. Without correct setting, kernel looked at the wrong offset on flash when loading the second apps and caused "TBF header not found" error.
> fix: correct total_size and binary_end_offset in TBF header of the app

- .github/workflows/compliance.yml
They switched to CMake from make, so we need to use a slightly different
way of building the official simulator.
> Compliance test fix for latest sail-riscv

- tests/hello/build.rs
This was slowing down builds slightly since it would force that binary to be recompiled every time.
With it referencing the correct files, the build can be cached.
> Fix the hello.elf build script to reference correct files

- emulator/periph/src/flash_ctrl.rs
- emulator/periph/src/i3c.rs
- emulator/periph/src/otp.rs
- registers/generated-emulator/src/el2_pic.rs
- registers/generated-emulator/src/i3c.rs
- registers/generated-emulator/src/main_flash.rs
- registers/generated-emulator/src/mbox.rs
- registers/generated-emulator/src/mci.rs
- registers/generated-emulator/src/otp.rs
- registers/generated-emulator/src/recovery_flash.rs
- registers/generated-emulator/src/root_bus.rs
- registers/generated-emulator/src/sha512_acc.rs
- registers/generated-emulator/src/soc.rs
- xtask/src/registers.rs
We were ignoring the array dimension, which caused the automatic peripherals to be missing registers.
We also simplified the `match` arms so that there would not be a ridiculous number of arms for the different addresses for large arrays.
While we're here, we can go ahead and remove the `size` paramter from peripheral methods. It's never used as we always have 32-bit registers.
> registers: Implement emulated register arrays correctly

- Cargo.lock
- Cargo.toml
- emulator/caliptra/src/caliptra.rs
Caliptra recently updated zerocopy to 0.8.8, so we can sync up our versions now.
> Update Calitpra core and zerocopy

- rom/src/fuses.rs
- rom/src/io.rs
- rom/src/main.rs
- rom/src/riscv.rs
- xtask/src/test.rs
In the ROM, we don't want to allow panics: we want to know explicitly any time we can reach a fatal error.
So we add a similar to test to Caliptra's to scan the ROM ELF for a symbol we inject when a panic is possible:
https://github.com/chipsalliance/caliptra-sw/blob/main/rom/dev/tests/rom_integration_tests/test_panic_missing.rs
We had to remove the usage of `{:x}` in formatting calls in the ROM, since current versions of Rust (incorrectly?) think it can panic.
Runtime will be allowed to panic, though we should take care to minimize the amount of calls, since we cannot reasonably recover from a kernel panic, but it is probably not possible to remove all panics from Tock.
> rom: Don't allow panics

- .github/workflows/build-test.yml
- emulator/app/src/i3c_socket.rs
- emulator/app/src/tests/mctp_util/common.rs
- emulator/app/src/tests/spdm_validator.rs
- runtime/capsules/src/mctp/driver.rs
This fixes a few issues
* We cancel the test if it hangs for more than 30 seconds
* We correct the target address (instead of the tag) when launching the test
* We reduce the wait from 5 seconds to 0.5 after sending a message
* If scheduling an upcall fails, we panic instead of ignoring the error.
* If the test fails, we set the exit code correctly.
I believe the SPDM validator test was failing before, but the exit code was not being set, so it appeared to be passing.
However, the SPDM validator test is still failing, but I believe it is correct to still be failing, since the failure is on a message type that we do not support yet. So, I've left the test disabled for now.
(It looks like Cargo will no longer automatically install the toolchain and needed modules, so I updated GHA to do …
> spdm: Set exit status correctly; fix target address in tests

- .github/workflows/build-test.yml
- .github/workflows/docs.yml
Also make it so that the toolchain is grabbed from `rust-toolchain.toml`.
> Fix docs build: rustup needs -y and curl doesn't like it

- .github/workflows/compliance.yml
And also do some other workflow cleanup (use checkout instead of clone, use working-directory instead of `cd`/`pushd`, `popd` is not necessary, checkout fixed git commits, and pre-install GMP.
> RISC-V compliance tests: install rustup toolchain manually

- builder/src/apps.rs
When the App binaries are not aligned to 4-bytes, tock throws an "App flash length not supported by MPU." error.
To fix this we will pad the App binary until it is aligned to 4-bytes, so that the next App's TBF will also be aligned to 4-bytes
The layout would be:
TBF for App1
App1.bin
TBF for App2
App2.bin
...
TBF is 132 bytes which is 4-byte aligned, so we just need to make sure that the app binaries are 4-bytes aligned.
> Align App binaries to 4-bytes

- runtime/apps/api/src/checksum.rs
- runtime/apps/api/src/lib.rs
Problem:
If libapi is included as a dependency of a tock app, the compiler will throw an exception that libapi is dependent on std lib so it can not be added.
Solution:
Add no_std in the libapi module lib.rs. Need to remove the test_checksum_overflow unit test case, since it will cause a stack overflow when run on a RISC compiler.
> Fix libapi can not be included as device app dependency

- common/pldm/src/message/firmware_update/pass_component.rs
- common/pldm/src/message/firmware_update/request_update.rs
- common/pldm/src/protocol/firmware_update.rs
- emulator/bmc/pldm-ua/src/update_sm.rs
- emulator/bmc/pldm-ua/tests/test_pass_component_table.rs
- emulator/bmc/pldm-ua/tests/test_update_component.rs
Support for PLDM PASS_COMPONENT and UPDATE_COMPONENT commands.
PASS_COMPONENT command passes the metadata of each component that needs to be updated one by one to the FD.
UPDATE_COMPONENT indicates to the FD which component will be updated.
Add unit tests for these 2 commands.
> [FW Update Agent] Implement PASS_COMPONENT and UPDATE_COMPONENT PLDM Commands

- Cargo.lock
- README.md
- builder/Cargo.toml
- builder/src/caliptra.rs
- builder/src/lib.rs
- emulator/app/src/main.rs
- tests/integration/Cargo.toml
- tests/integration/src/lib.rs
- xtask/src/main.rs
- xtask/src/runtime.rs
Caliptra Core will now always run, since we will start using it soon for mailbox commands.
To make it easier to use, we now automatically build Caliptra ROM, FW, and SoC manifest if they are not passed in.
I factored out the `CaliptraBuilder` struct to make it easier for it to reason about when to automatically build the FW if not provided, when to build the SoC manifest if not provided, etc.
> Run Caliptra Core by default; autobuild its FW

- Cargo.lock
- emulator/bmc/pldm-fw-pkg/Cargo.toml
- emulator/bmc/pldm-fw-pkg/src/main.rs
- emulator/bmc/pldm-fw-pkg/src/manifest.rs
- emulator/bmc/pldm-fw-pkg/tests/test_decode.rs
- emulator/bmc/pldm-fw-pkg/tests/test_encode.rs
- emulator/bmc/pldm-ua/Cargo.toml
- emulator/bmc/pldm-ua/src/update_sm.rs
- emulator/bmc/pldm-ua/tests/test_download.rs
Support for downloading the PLDM Firmware by implementing the RequestFirmwareData and TransferComplete PLDM commands. Some changes are also needed in the pldm-fw-pkg lib.
1. Changes in PLDM-FW-PKG lib.
(The PLDM-FW-PKG library is responsible for encoding and decoding PLDM FW package files. In PLDM FW update, this lib is used to decode the package file, so that the firmware content can be retrieved by the update agent)
- Currently, when the pldm-fw-pkg library decodes a PLDM package file, it will copy the firmware binaries in the pldm-fw-pkg into separate files, it will also return a FirmwareManifest struct that contains the file paths of the binaries created. In this patch, the firmware binary is stored into separate local buffers within the FirmwareManifest struct, so that the PLDM …
> [FW Update Agent] Implement RequestFirmwareData and TransferComplete PLDM Commands

- emulator/bmc/pldm-ua/src/lib.rs
- emulator/bmc/pldm-ua/src/timer.rs
- emulator/bmc/pldm-ua/src/update_sm.rs
- emulator/bmc/pldm-ua/tests/test_post_download.rs
Implement the VerifyComplete, ApplyComplete, ActivateFw and CancelUpdateComponent, GetStatus PLDM Commands.
After download is completed, update_sm will wait for VerifyComplete from device, then the ApplyComplete. If there are no more components to update, the update_sm will send an ActivateFw.
If the device has components with 'self-activation' flag set, update_sm will send periodically GetStatus commands until it gets a response that the device has succesfully activated the Firmware.
If there are any failures, in Verify, Apply or Activate stages, the update_sm will send a CancelUpdateComponent and will terminate the update.
A timer module is created to support the timer related actions in the update_sm.
> [FW Update Agent] Support Post Download PLDM Commands

- Cargo.lock
- Cargo.toml
- registers/systemrdl-new/Cargo.toml
- registers/systemrdl-new/src/ast.rs
- registers/systemrdl-new/src/bits.rs
- registers/systemrdl-new/src/file_source.rs
- registers/systemrdl-new/src/lexer.rs
- registers/systemrdl-new/src/lib.rs
- registers/systemrdl-new/src/parser.rs
- registers/systemrdl-new/src/string_arena.rs
- registers/systemrdl-new/src/token.rs
- registers/systemrdl-new/src/token_iter.rs
Uses the [winnow](https://crates.io/crates/winnow) parser-combinator library to write a new SystemRDL parser.
The new RDL changes to our registers, in particular MCI, don't show up with the existing parser. The existing parser is a bit of a hack, and skips over a lot of the pieces of the spec that we don't support.
The generator also makes a lot of assumptions about how the RDL files are structured, and those those assumptions don't seem to hold for the new RDL as well.
So, I started a (mostly) from-scratch rewrite of the entire parser using `winnow`, which allows us to implement a parser for the entire SystemRDL 2.0 grammar. The grammar is virtually identical to what appears in the [SystemRDL 2.0
specification](https://www.accellera.org/images/downloads/standards/systemrdl/SystemRDL_2.0_J …
> New SystemRDL 2.0 parser in winnow

- .github/workflows/build-test.yml
The SPDM validator's file were built with an old version of CMake (<= 3.5). CMake (in 4.0.0) just dropped support for those build scripts.
So, we download and install the last version of CMake 3.x that supports the SPVM validator build scripts as part of our CI pipeline.
> Downgrade cmake to 3.x so that SPDM validator can run

- .github/workflows/build-test.yml
- builder/src/apps.rs
- runtime/apps/spdm/spdm-lib/src/cert_mgr.rs
- runtime/apps/spdm/spdm-lib/src/commands/certificate_rsp.rs
- runtime/apps/spdm/spdm-lib/src/commands/digests_rsp.rs
- runtime/apps/spdm/spdm-lib/src/commands/mod.rs
- runtime/apps/spdm/spdm-lib/src/config.rs
- runtime/apps/spdm/spdm-lib/src/context.rs
- runtime/apps/spdm/spdm-lib/src/protocol/common.rs
This PR introduces support for handling the SPDM `get-certificate` command and minor adjustments to `get-digest` command due to the relocation of common functions.
> Add support for SPDM GET CERTIFICATE command handling

- Cargo.lock
- Cargo.toml
- runtime/userspace/api/caliptra-api/Cargo.toml
- runtime/userspace/api/caliptra-api/src/crypto/error.rs
- runtime/userspace/api/caliptra-api/src/crypto/hash.rs
- runtime/userspace/api/spdm-lib/Cargo.toml
- runtime/userspace/api/spdm-lib/src/cert_mgr.rs
- runtime/userspace/api/spdm-lib/src/codec.rs
- runtime/userspace/api/spdm-lib/src/context.rs
- runtime/userspace/api/spdm-lib/src/error.rs
- runtime/userspace/api/spdm-lib/src/transport.rs
- runtime/userspace/apps/spdm/src/main.rs
- runtime/userspace/apps/spdm/src/riscv.rs
This PR 
1. Makes MCTP transport a trait implementation
2. Removes thiserror crate and uses enums to define errors in SPDM
> Make Transport genertic and remove thiserror dependency in SPDM

- platforms/emulator/runtime/userspace/apps/image-loader/src/main.rs
Image-loader app will execute test_exit(0) even there are no integ tests
related to it are running, this causes other integ tests to exit
immediately (e.g. SPDM_VALIDATOR).
Add a condition to check if the integ test features flags are set before
deciding if exit is needed.
> Prevent image-loader app from exiting when test is successful

- emulator/app/src/main.rs
- emulator/bmc/pldm-ua/src/update_sm.rs
- emulator/cpu/src/cpu.rs
- runtime/userspace/api/caliptra-api/src/image_loading/pldm_fdops.rs
- tests/integration/src/lib.rs
- tests/integration/src/test_soc_boot.rs
* Add test cases to simulate invalid configurations
- incorrect image id
- unauthorized fw data
- incorrect load address
- incorrect PLDM descriptor
- incorrect PLDM component ID
- corrupted PLDM package
- PLDM package has lower version than device's
* Have the PLDM UA emulator exit with an error code when it detects an
error. This allows the integ test to check for errors.
* Fixed an issue in the image loader PLDM handle_component ops where it
returns with an Err() instead with an Ok(response_code).
* Fixed the issue that sometimes emulator exits early
This was caused by the MCU emulator throwing a Memory Load Access Fault
when handling external interrupt. In some cases, the mode is still in
User mode before accessing the interrupt vector table causing an access fault.
To fix the issue, …
> Additional Integration test cases for flash and streaming boot

- common/pldm/src/message/firmware_update/get_fw_params.rs
- xtask/src/pldm_fw_pkg.rs
GetFirmwareParameter command's active version string has a dynamic length and should be encoded/decoded manually. Currently, it's inside the fixed parameters struct which is encoded/decoded by zerocopy. As a fix, this string is moved out of the fixed parameters struct.
Also fixed the xtask command to decode the PLDM FW package, it was calling the incorrect function to decode the FW package. It was calling to decode a manifest file, but the function is for decoding the firmware package
> Fix PLDM encoding of GetFirmwareParameters command

- Cargo.lock
- Cargo.toml
- README.md
- hw/model/Cargo.toml
- hw/model/src/lib.rs
- hw/model/src/xi3c/controller.rs
- hw/model/src/xi3c/mod.rs
- xtask/src/header.rs
This Xilinx AXI I3C controller is an IP block we use in the FPGA to be the I3C controller attached to our AXI bus.
This is mostly a translation of the C driver along with some Rust cleanup and bug fixes.
Docs: https://docs.amd.com/r/en-US/pg439-axi-i3c/
Original C source: https://github.com/Xilinx/embeddedsw/tree/master/XilinxProcessorIPLib/drivers/i3c/src
> fpga: Add Xilinx AXI I3C controller driver

- Cargo.lock
- hw/model/Cargo.toml
- hw/model/src/bus_logger.rs
- hw/model/src/bus_logger_mcu.rs
- hw/model/src/lib.rs
- hw/model/src/model_emulated.rs
- hw/model/src/model_fpga_realtime.rs
- hw/model/src/output.rs
- rom/src/riscv.rs
These are pared down versions of the Caliptra hw-model: https://github.com/chipsalliance/caliptra-sw/tree/main-2.x/hw-model
I'll add more of those pieces as we add in more Caliptra functionality.
This so far will boot the ROM and runtime on the FPGA if you run:
```shell
cargo t -p mcu-hw-model --features fpga_realtime -- --test model_fpga_realtime::test::test_new_unbooted --exact --nocapture
```
Based on #200
> hw/model: Add in basic emulated and FPGA hardware models

- hw/model/src/model_emulated.rs
- hw/model/src/model_fpga_realtime.rs
I merged #202 without rebasing after #208, which added a feature argument to the rom_build.
> hw/model: rom_build now requires the feature argument

- builder/src/runtime.rs
- runtime/userspace/syscall/src/mailbox.rs
- tests/integration/src/test_soc_boot.rs
The SOC boot integration tests were previously disabled since the compiled user app with the soc boot features enabled will not fit RAM.
To be able to fit the App, the DATA_RAM_SIZE is decreased by 8KB.
With the Image loading task running the integ tests with the SPDM task, an issue with the mailbox syscall was encountered:
Error copying from mailbox: MailboxRespTypeTooSmall
It was found that there is a race condition between the Image Loading task and the SPDM Task.
Image Loading Task executes a mailbox command. After mailbox driver calls the upcall for the response of this command, the SPDM task immediately enqueues a command to the mailbox. However, the Image Loading Task will call:
S::unallow_ro(self.driver_num, mailbox_ro_buffer::INPUT);
S::unallow_rw(self.driver_num, …
> Enable SOC BOOT Integration Tests

- Cargo.lock
- builder/Cargo.toml
- builder/src/flash_image.rs
- common/flash-image/src/lib.rs
- docs/src/flash_layout.md
- rom/src/recovery.rs
- runtime/userspace/api/caliptra-api/src/image_loading/flash_client.rs
- runtime/userspace/api/caliptra-api/src/image_loading/pldm_client.rs
- runtime/userspace/api/caliptra-api/src/image_loading/pldm_fdops.rs
- Use the common flash-image format defined in the common library used for builder, instead of redefining it in the builder.
- Make the flash header format more extensible by adding a pointer to where the payload begins. This allows the header to be extended in the future
- Instead of the payload checksum, have a checksum per image to be added in the TOC. This allows per image update without needing to update the payload checksum.
- Update doc
> Update Flash Format

- runtime/kernel/capsules/src/mctp/control_msg.rs
- runtime/kernel/capsules/src/mctp/mux.rs
This commit introduces a new MCTP control command `GetVersionSupport` to retrieve version support information.
> feat(mctp): Add support for GetVersionSupport command

- emulator/app/src/doe_mbox_fsm.rs
- emulator/app/src/emulator.rs
- emulator/app/src/main.rs
- emulator/app/src/tests/doe_discovery.rs
- emulator/app/src/tests/doe_transport_loopback.rs
- emulator/app/src/tests/doe_user_loopback.rs
- emulator/app/src/tests/doe_util/common.rs
- emulator/app/src/tests/spdm_responder_validator/doe.rs
These now sleep a deterministic amount of time (measured by CPU cycles), so won't be dependent on the speed of the host computer.
This also means we can trim down the sleep times, which reduces how long this test takes by 50% (down from 2.5 hours to 1.2 hours or so).
Next we should do the same for all of the emulator tests that use `sleep`.
> Make SPDM DOE tests deterministic

- emulator/bmc/pldm-ua/src/daemon.rs
- emulator/bmc/pldm-ua/src/discovery_sm.rs
- emulator/bmc/pldm-ua/src/timer.rs
- emulator/bmc/pldm-ua/src/update_sm.rs
- emulator/bmc/pldm-ua/tests/common.rs
- emulator/bmc/pldm-ua/tests/test_discovery.rs
- emulator/bmc/pldm-ua/tests/test_get_fw_parameters.rs
When Update Agent sends a packet, it will schedule a timer and wait for device to respond. If the timer expires, the packet will be resent.
Update agent will retry up to 3 times every 3 seconds. This is done on both discovery and firmware update state machines.
> Implement PLDM Update Agent Retries

- .cargo/config.toml
- .github/workflows/fpga.yml
- README.md
- builder/src/all.rs
- docs/src/fpga.md
- hw/model/src/model_fpga_realtime.rs
- xtask/Cargo.toml
- xtask/src/main.rs
This is a basic test case that boots the FPGA and checks the MCI boot
status.
This change also removes "fpga_realtime" as an enabled dependency in the xtask crate.
Since the dependency features of a workspace are resolved via a union,
this enabled "fpga_realtime" for the rest of the workspace.
> FPGA: Add new_unbooted test case

- Cargo.lock
- Cargo.toml
- hw/model/src/lib.rs
- hw/model/src/mcu_mgr.rs
- hw/model/src/model_emulated.rs
- hw/model/src/model_fpga_realtime.rs
This will be used by integration tests to support accessing registers as if from the external SoC. This also makes it easy to make tests that work with both the emulator and the FPGA.
This can been tested locally and on the FPGA, tests will be added in a follow on PR.
> Add an MCU manager to the HW model.

- Cargo.lock
- Cargo.toml
- platforms/emulator/config/src/flash.rs
- platforms/emulator/runtime/userspace/apps/user/src/image_loader/mod.rs
- rom/src/fw_hitless_update.rs
- runtime/userspace/api/caliptra-api/src/firmware_update/mod.rs
- runtime/userspace/api/caliptra-api/src/firmware_update/pldm_client.rs
- runtime/userspace/api/caliptra-api/src/firmware_update/pldm_context.rs
- runtime/userspace/api/caliptra-api/src/firmware_update/pldm_fdops.rs
- runtime/userspace/api/caliptra-api/src/image_loading/mod.rs
- tests/integration/src/test_firmware_update.rs
Verify the firmware package after downloading the firmware update package from the PLDM update agent and before activating the images.
Steps:
1. Download the firmware package to MCU
2. Parse the components of the package
3. Verify the SOC manifest through mailbox command (without setting it in Caliptra)
4. Verify the downloaded MCU image by getting sha384 of image and comparing it with downloaded Manifest's SHA.
4. Verify the downloaded SOC images by getting sha384 of images and comparing it with downloaded Manifest's SHAs.
5. Verify and Activate Caliptra fw using FIRMWARE_LOAD mbox command.
6. Activate MCU FW using Hitless Update Reset
7. After boot, set the downloaded manifest to Caliptra using SET_AUTH_MANIFEST mbox command
8. Use image loading to load the rest of the SOC images from …
> Firmware Update Image Verification

- .github/workflows/fpga.yml
Also removed the extra `xtask` build.
This reduces the wall clock time for the FPGA tests significantly. Now cross-compiling should take ~5-6 mins with a warm cache.
> CI: Do not vendor OpenSSL crate

- .gitignore
- hw/fpga/util/README.md
- hw/fpga/util/build-and-deploy-tests-to-fpga.sh
- hw/fpga/util/copy-fpga-tests-to-board.sh
- hw/fpga/util/cross-compiling/Dockerfile
- hw/fpga/util/cross-compiling/build-fpga-tests.sh
- hw/fpga/util/run-fpga-tests.sh
This add tooling for building, deploying, and running FPGA tests on the Versal FPGA board. This demonstrates how to cross compile tests (on a more power host machine) before copying them to the FPGA to be dispatched.
> [tooling] add shell scripting for deploying FPGA tests

- .gitignore
- docs/src/fpga.md
- xtask/src/fpga.rs
- xtask/src/main.rs
This change adds:
* Add subcommand to manage FPGA life cycle.
* Add command to run tests on an FPGA over SSH.
* Add command to build and copy firmware to FPGA.
* Add command to build and copy test binaries to FPGA.
* Add command to bootstrap FPGA.
I plan to do more clean up / feature work, but this should help folks quickly iterate on FPGA tests.
> FPGA Xtask changes

- hw/model/src/fpga_regs.rs
- hw/model/src/model_fpga_realtime.rs
This makes the FPGA significantly more stable and should remove the need to rebooting the FPGA between runs occasionally.
> fpga: Reset AXI before and after test

- xtask/src/fpga.rs
* Recursing submodules is unnecessary.
* Check if `caliptra-mcu-sw` exists befoer cloning.
> xtask: Speed up FPGA bootstrap

- docs/src/fpga.md
- xtask/src/fpga.rs
This updates the xtask flow for executing FPGA tests by enabling running a single specified task instead of the entire test suite.
> [xtask] enable dispatching a single FPGA test

- Cargo.lock
- Cargo.toml
- builder/src/all.rs
- builder/src/caliptra.rs
- emulator/app/src/emulator.rs
- emulator/cbinding/src/lib.rs
- emulator/cbinding/src/simple_test.rs
- emulator/periph/src/lib.rs
- emulator/periph/src/otp.rs
- hw/model/src/lib.rs
- hw/model/src/model_emulated.rs
- rom/src/cold_boot.rs
- rom/src/rom.rs
- tests/integration/src/lib.rs
- tests/integration/src/test_firmware_update.rs
- tests/integration/src/test_soc_boot.rs
- xtask/src/runtime.rs
- MCU ROM retrieves SoC Manifest SVN and Max SVN values and passes it to Caliptra using SoC interface.
- Add logic in MCU ROM to monitor Caliptra for Fatal Errors while waiting for FW to be ready. Caliptra will signal a fatal error if the SVN check fails. In this way, MCU will propagate the fatal error to SoC.
- Added SoC Manifest SVN to the OTP emulator peripheral
- Add arguments to the emulator runner to pass SoC Manifest SVN
- Add integration test to verify SoC Manifest Verification
> Pass SoC Manifest SVN fuse values to Caliptra

- hw/fpga/openocd_ss.txt
- hw/fpga/src/caliptra_package_top.v
This aligns the JTAG pin orderings across all TAPs (core, lcc, and mcu) as:
1. tck
2. tms
3. tdi
4. trst
5. tdo
Additionally, this fixes the openocd configuration script to use the same JTAG pin orderings. This partially addresses #363 by enabling connecting to the LCC TAP (along with the other TAPs).
With this fix, I am able to successfully connect to the LCC TAP with OpenOCD.
> [fpga] fix JTAG pin orderings

- hw/model/src/lib.rs
- hw/model/src/model_fpga_realtime.rs
The default lifecycle state was being set to prod which later would later cause it to fail the Caliptra firmware integrity checks because the built image uses ML-DSA by default, but the hardware model uses LMS by default.
> Fix FPGA HW Model being unable to run recovery flow.

- .github/workflows/build-test.yml
- .github/workflows/fpga.yml
- builder/src/all.rs
- builder/src/caliptra.rs
- hw/model/src/lib.rs
- hw/model/src/model_emulated.rs
- tests/integration/src/lib.rs
- tests/integration/src/test_firmware_update.rs
- tests/integration/src/test_mctp_capsule_loopback.rs
- tests/integration/src/test_pldm_fw_update.rs
- tests/integration/src/test_soc_boot.rs
- xtask/src/fpga.rs
- xtask/src/main.rs
- xtask/src/runtime.rs
- xtask/src/test.rs
The `FwId` and `REGISTERED_FW` abstraction doesn't quite work for specifying the different runtime binaries since they are in a different crate for FPGA. There's additional complexity in that a different runtime would also require a different SoC manifest to authorize it. So I added a slightly different mechanism for building and packaging them in the the `all-fw.zip` bundle.
The downside is that the FPGA test is flaky due to it halting when going through the full recovery flow to load MCU runtime.
> Onboard mctp-capsule-loopback test to FPGA CI

- emulator/periph/src/lib.rs
- emulator/periph/src/uart.rs
So that the Tock panic prints correctly finally:
```
╔═══════════╤══════════════════════════════════════════╗
║  Address  │ Region Name    Used | Allocated (bytes)  ║
╚0x4007F4B0═╪══════════════════════════════════════════╝
│ Grant Ptrs      120
│ Upcalls         320
│ Process         756
0x4007F004 ┼───────────────────────────────────────────
```
I'll also port this to `caliptra-sw` for the HwModel output.
> emulator: Support UTF8 characters in output

- hw/model/src/lcc.rs
- tests/integration/src/jtag/test_lc_transitions.rs
This adds an E2E FPGA test that performs a PROD-->RMA LC transition.
This partially addresses: https://github.com/chipsalliance/caliptra-ss/issues/233
Note, this is expected to fail until #454 is resolved. An TODO has been left in the code with this comment.
> [test] add RMA unlock test

- Cargo.lock
- Cargo.toml
- hw/model/src/lcc.rs
- tests/integration/src/jtag/test_jtag_taps.rs
This revs the caliptra-sw repo version to account for the changes in: https://github.com/chipsalliance/caliptra-sw/pull/2540
> [deps] rev caliptra-sw repo version

- docs/src/fpga.md
- xtask/src/fpga/configurations.rs
- xtask/src/fpga/mod.rs
- xtask/src/fpga/utils.rs
- Add checks that both the FPGA and HOST have the correct dependencies installed.
- Store configuration in RAM so we can tell if FPGA needs to be bootstrapped.
> [xtask]: FPGA Workfow docs and usage improvements

- Cargo.lock
- builder/src/apps.rs
- hw/model/src/model_fpga_realtime.rs
- platforms/emulator/runtime/src/board.rs
- platforms/emulator/runtime/userspace/apps/example/src/main.rs
- platforms/emulator/runtime/userspace/apps/example/src/riscv.rs
- platforms/emulator/runtime/userspace/apps/user/src/image_loader/mod.rs
- platforms/emulator/runtime/userspace/apps/user/src/image_loader/pldm_fdops_mock.rs
- platforms/emulator/runtime/userspace/apps/user/src/main.rs
- platforms/emulator/runtime/userspace/apps/user/src/mcu_mbox/mod.rs
- platforms/emulator/runtime/userspace/apps/user/src/spdm/mod.rs
- platforms/fpga/runtime/Cargo.toml
- platforms/fpga/runtime/src/board.rs
- runtime/kernel/capsules/src/lib.rs
- runtime/kernel/capsules/src/system.rs
- runtime/kernel/components/src/lib.rs
- runtime/kernel/components/src/system.rs
- runtime/userspace/syscall/src/lib.rs
- runtime/userspace/syscall/src/system.rs
- tests/integration/src/test_pldm_fw_update.rs
- Test PLDM FW update protocol in FPGA by enabling the pldm_fw_update_e2e test
- Add MCI and MBOX SRAM drivers in FPGA board.rs since Image Loading App depends on it.
- Fix a bug in pldm update e2e test application, where the application doesn't exit since it's waiting for a SIGNAL() that hasn't been triggered. Moved the SIGNAL() into the pldm_fdops and trigger it on the last stage of PLDM which is activation.
- Update sleep_emulator_ticks while test is stepping.
> Enable PLDM fw update e2e test in FPGA

- platforms/emulator/runtime/kernel/drivers/dma/src/nodma.rs
The fake DMA driver that does manual SW copy of data from source to destination address can throw Misaligned load Exception if the source or destination is not 4-byte aligned. This is because the driver transfers in 4-byte chunks.
Transfer in bytes instead of words since is not assured that application will pass 4-byte aligned source or destination address.
> Fix Misaligned exception on noDMA driver

- Cargo.lock
- docs/src/fpga.md
- xtask/Cargo.toml
- xtask/src/fpga/configurations.rs
- xtask/src/fpga/mod.rs
- xtask/src/fpga/utils.rs
This removes the need for specifying `caliptra-sw` as a flag.
> [xtask-fpga]: Parse xtask Cargo.toml for caliptra_sw path
