emulator/periph/src/i3c.rs, runtime/i3c/src/core.rs
Fix private writes to the target.
=> add i3c peripheral and driver fixes

runtime/apps/libtock/ufmt/utils/Cargo.toml
https://github.com/chipsalliance/caliptra-mcu-sw/security/dependabot/2
=> Update heapless to avoid use after free bug

tests/integration/src/lib.rs
We currently have files and ports that the MCU emulator is using that can conflict if we are running two emulators at once, so we force the tests to only run one at a time.
=> Run one integration test at a time

Cargo.lock, runtime/apps/api/src/crypto/hash.rs, runtime/apps/api/src/image_loading.rs, runtime/apps/api/src/mailbox.rs, runtime/apps/api/tests/image_loading_test.rs, runtime/apps/example/src/main.rs, runtime/apps/example/src/test_caliptra_crypto.rs, runtime/apps/example/src/test_caliptra_mailbox.rs, runtime/apps/example/src/test_pldm_request_response.rs, runtime/apps/pldm/pldm-app/src/main.rs, runtime/apps/pldm/pldm-lib/src/cmd_interface.rs, runtime/apps/pldm/pldm-lib/src/daemon.rs, runtime/apps/pldm/pldm-lib/src/firmware_device/fd_context.rs, runtime/apps/pldm/pldm-lib/src/firmware_device/fd_ops.rs, runtime/apps/pldm/pldm-lib/src/transport.rs, runtime/apps/spdm/spdm-app/src/main.rs, runtime/apps/spdm/spdm-lib/src/cert_mgr.rs, runtime/apps/spdm/spdm-lib/src/commands/algorithms_rsp.rs, runtime/apps/spdm/spdm-lib/src/commands/capabilities_rsp.rs, runtime/apps/spdm/spdm-lib/src/commands/certificate_rsp.rs, runtime/apps/spdm/spdm-lib/src/commands/digests_rsp.rs, runtime/apps/spdm/spdm-lib/src/commands/version_rsp.rs, runtime/apps/spdm/spdm-lib/src/context.rs, runtime/apps/spdm/spdm-lib/src/transport.rs, runtime/apps/syscall/Cargo.toml, runtime/apps/syscall/src/dma.rs, runtime/apps/syscall/src/flash.rs, runtime/apps/syscall/src/lib.rs, runtime/apps/syscall/src/mailbox.rs, runtime/apps/syscall/src/mctp.rs
Remove Syscalls generics from API surface
=> remove Syscalls generics from API surface

docs/src/external_mailbox_cmds.md, docs/src/mci_mailbox_cmd.md
This PR outlines the external mailbox commands that enable SoC agents to interact with the Caliptra MCU via MCI mailbox.
=> External Mailbox Command Spec 

Cargo.lock, Cargo.toml, common/config/src/lib.rs, platforms/common/Cargo.toml, platforms/common/src/lib.rs, platforms/common/src/pmp_config.rs, platforms/emulator/config/src/lib.rs, platforms/emulator/runtime/Cargo.toml, platforms/emulator/runtime/src/board.rs, platforms/fpga/config/src/lib.rs, platforms/fpga/runtime/Cargo.toml, platforms/fpga/runtime/src/board.rs, runtime/kernel/veer/src/pmp.rs
=> Calculate PMP Regions from McuMemoryMap

Cargo.lock, docs/src/doe.md, platforms/emulator/runtime/kernel/drivers/doe_mbox/src/lib.rs, platforms/emulator/runtime/src/tests/doe_transport_test.rs, runtime/kernel/capsules/Cargo.toml, runtime/kernel/capsules/src/doe/driver.rs, runtime/kernel/capsules/src/doe/mod.rs, runtime/kernel/capsules/src/doe/protocol.rs, runtime/kernel/capsules/src/lib.rs, runtime/kernel/drivers/doe/src/hil.rs
This PR introduces the DOE capsule framework.
The capsule still needs to be instantiated and integrated into the platform.
=> Add DOE Capsule

Cargo.lock, emulator/periph/src/mci.rs, hw/model/Cargo.toml, hw/model/src/lib.rs, hw/model/src/model_emulated.rs, hw/model/src/model_fpga_realtime.rs, hw/model/src/vmem.rs, rom/src/boot_status.rs, rom/src/cold_boot.rs, rom/src/lib.rs, romtime/src/mci.rs, xtask/src/fpga.rs
So that tests and integrators can tell where the ROM has gotten to.
I based this on Caliptra core: https://github.com/chipsalliance/caliptra-sw/blob/main-2.x/common/src/boot_status.rs
=> Add ROM boot status

hw/model/src/lib.rs, hw/model/src/model_emulated.rs, hw/model/src/model_fpga_realtime.rs
Not tested yet, but wanted to get this started to help folks who are making changes to the HwModel code and give an example of how these emulator / FPGA AXI integrations will work.
=> Implement more of hw model for communicating with Caliptra

Cargo.lock, emulator/app/src/emulator.rs, emulator/cbinding/Cargo.toml, emulator/cbinding/src/lib.rs, emulator/cbinding/src/simple_test.rs, emulator/periph/Cargo.toml, emulator/periph/src/otp.rs, hw/model/src/lib.rs, hw/model/src/model_emulated.rs, hw/model/src/model_fpga_realtime.rs, rom/src/rom.rs, runtime/userspace/api/spdm-lib/src/pci_sig/ide_km.rs
This is necessary to run Caliptra tests.
=> Set PQC type from fuses

builder/src/all.rs
This adds a static cache to `FirmwareBinaries::from_env`. This makes the
function performant to call multiple times.
I believe there is more cleanup / refactoring to the builder that needs to be done, but this should keep the FPGA tests from spending a lot of time de-compressing the zip file.
=> Cache FirmwareBinaries::from_env

docs/src/ide_km.md, runtime/userspace/api/spdm-lib/src/pci_sig/ide_km.rs
=> correct IDE key size

.github/workflows/fpga.yml
=> Add sccache to FPGA build

.github/workflows/fpga.yml
This makes it easier to verify CI FPGA changes.
=> Add FPGA workflow trigger

rom/src/fw_hitless_update.rs
After firmware update, MCU Runtime sends out a Populate Dev Cert Mailbox command, however it fails. This doesn't happen if the reset is due to cold boot.
This was due to the ROM FW Hitless Update flow not finishing the previous mailbox command properly after firmware update. It didn't wait for the mailbox command status to change to CMD_COMPLETE before allowing the MCU Runtime to execute another command.
During FW Update, MCU downloads the new firmware and then sends an ACTIVATE_FIRMWARE command to Caliptra. This initiates an MCU reset. After MCU reset, MCU ROM FW Hitless Update flow should have finished the ACTIVATE_FIRMWARE command transaction properly and wait for the command status to become CMD_COMPLETE.
The fix is to call the finish_mailbox_resp() API to properly wait for the …
=> Fix mailbox command failure after firmware update

xtask/src/fpga.rs
Add an option the FPGA test xtask flow to stream test output to the console for test debugging.
=> [xtask] enable streaming test output

.github/workflows/fpga.yml, Cargo.lock, Cargo.toml, builder/src/all.rs, builder/src/firmware.rs, builder/src/lib.rs, builder/src/rom.rs, hw/model/src/lib.rs, hw/model/src/mcu_mgr.rs, hw/model/test-fw/Cargo.toml, hw/model/test-fw/build.rs, hw/model/test-fw/mailbox_responder.rs, xtask/src/fpga.rs
This adds a mechanism to run a test ROM in the HW model. The first test checks the MBOX0 functionality. These could be expanded to cover more drivers and register access.
=> Add HW model test ROM capability similar to Caliptra.

xtask/src/fpga.rs
I tend to have a few active folders at a time.
=> [Xtask FPGA]: Support any folder as a caliptra-sw build target

.github/workflows/fpga.yml, Cargo.lock, Cargo.toml, common/poll/Cargo.toml, common/poll/src/lib.rs, hw/model/Cargo.toml, hw/model/src/lcc.rs, hw/model/src/lib.rs, hw/model/src/model_fpga_realtime.rs, rom/src/fuses.rs, tests/integration/src/lib.rs, tests/integration/src/test_lc_transitions.rs
This adds an E2E test that performs a raw unlock lifecycle transition via the LCC JTAG TAP. This partially addresses #233.
=> [test] add raw unlock LC transition FPGA test

Cargo.lock, Cargo.toml, hw/model/src/lib.rs, hw/model/test-fw/mailbox_responder.rs
Adds the other tests from `test_mailbox_execute` from caliptra-sw.
=> [Mailbox] Add more tests.

xtask/src/fpga/configurations.rs, xtask/src/fpga/mod.rs, xtask/src/fpga/utils.rs
Tidy code up a little bit. Split into smaller files and implement FPGA actions into different structures.
=> Xtask FPGA CLI Refactor

xtask/src/fpga/configurations.rs
Accidentally introduced the wrong path in a refactor
=> [xtask-fpga]: Fix caliptra_sw path
